cmake_minimum_required(VERSION 3.8)
project(optitrack_listener2)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

set(LIBNATNET_SDK_LIBRARY ${CMAKE_CURRENT_SOURCE_DIR}/NatNetSDK/lib/libNatNet.so)
set(NATNET_INCLUDE_DIR
  ${CMAKE_CURRENT_SOURCE_DIR}/NatNetSDK/include
)

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(builtin_interfaces REQUIRED)
find_package(std_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(px4_msgs REQUIRED)
find_package(tf2 REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(eigen3_cmake_module REQUIRED)
find_package(Eigen3 REQUIRED)

include_directories(
  include
  ${NATNET_INCLUDE_DIR}
)

# executable optitrack_listener
add_executable(optitrack_listener src/optitrack_listener.cpp)
target_include_directories(optitrack_listener PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>)
target_compile_features(optitrack_listener PUBLIC c_std_99 cxx_std_17)  # Require C99 and C++17
ament_target_dependencies(
  optitrack_listener
  "rclcpp"
  "builtin_interfaces"
  "std_msgs"
  "geometry_msgs"
  "sensor_msgs"
  "nav_msgs"
  "px4_msgs"
  "tf2"
  "tf2_ros"
  "Eigen3"
)
install(TARGETS optitrack_listener
  DESTINATION lib/${PROJECT_NAME})


# executable mocap2_driver
add_executable(mocap2_driver src/mocap2_driver.cpp)
target_include_directories(mocap2_driver PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>)
target_compile_features(mocap2_driver PUBLIC c_std_99 cxx_std_17)  # Require C99 and C++17
ament_target_dependencies(
  mocap2_driver
  "rclcpp"
  "builtin_interfaces"
  "std_msgs"
  "geometry_msgs"
  "sensor_msgs"
  "nav_msgs"
  "px4_msgs"
  "tf2"
  "tf2_ros"
  "Eigen3"
)
target_link_libraries(mocap2_driver ${LIBNATNET_SDK_LIBRARY})
set_target_properties(mocap2_driver PROPERTIES
  BUILD_WITH_INSTALL_RPATH TRUE
  INSTALL_RPATH "$ORIGIN")
install(TARGETS mocap2_driver
  DESTINATION lib/${PROJECT_NAME})
install(FILES ${LIBNATNET_SDK_LIBRARY}
  DESTINATION lib/${PROJECT_NAME})


# Install launch files
install(DIRECTORY 
    launch
    DESTINATION share/${PROJECT_NAME}
    )

# Install config files
install(DIRECTORY 
    config
    DESTINATION share/${PROJECT_NAME}
    ) 



if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()
