%YAML:1.0

use_sim_time: true
verbosity: "DEBUG"

use_fej: true
integration: "rk4"
use_stereo: false
max_cameras: 2

calib_cam_extrinsics: false
calib_cam_intrinsics: false
calib_cam_timeoffset: false
calib_imu_intrinsics: false
calib_imu_g_sensitivity: false

max_clones: 15
max_slam: 150
max_slam_in_update: 50
max_msckf_in_update: 40
dt_slam_delay: 3

gravity_mag: 9.80

feat_rep_msckf: "GLOBAL_3D"
feat_rep_slam: "GLOBAL_3D"
feat_rep_aruco: "GLOBAL_3D"

try_zupt: true
zupt_chi2_multipler: 0
zupt_max_velocity: 0.05
zupt_noise_multiplier: 50
zupt_max_disparity: 1.5
zupt_only_at_beginning: true

init_window_time: 2.0
init_imu_thresh: 0.3
init_max_disparity: 2.0
init_max_features: 75

init_dyn_use: false
init_dyn_mle_opt_calib: false
init_dyn_mle_max_iter: 50
init_dyn_mle_max_time: 0.5
init_dyn_mle_max_threads: 6
init_dyn_num_pose: 6
init_dyn_min_deg: 10.0

init_dyn_inflation_ori: 10
init_dyn_inflation_vel: 100
init_dyn_inflation_bg: 10
init_dyn_inflation_ba: 100
init_dyn_min_rec_cond: 1e-15

init_dyn_bias_g: [0.0, 0.0, 0.0]
init_dyn_bias_a: [0.0, 0.0, 0.0]

record_timing_information: false
record_timing_filepath: "/tmp/traj_timing.txt"

save_total_state: false
filepath_est: "/tmp/ov_estimate.txt"
filepath_std: "/tmp/ov_estimate_std.txt"
filepath_gt: "/tmp/ov_groundtruth.txt"

use_klt: true
klt_win_size: 25
klt_max_iter: 25
klt_max_level: 5
num_pts: 300
fast_threshold: 15
grid_x: 8
grid_y: 8
min_px_dist: 10
knn_ratio: 0.70
track_frequency: 20.0
downsample_cameras: false
num_opencv_threads: 2
histogram_method: "HISTOGRAM"

use_aruco: false
num_aruco: 1024
downsize_aruco: true

up_msckf_sigma_px: 4
up_msckf_chi2_multipler: 10
up_slam_sigma_px: 4
up_slam_chi2_multipler: 10
up_aruco_sigma_px: 1
up_aruco_chi2_multipler: 1

use_mask: false

# Percorsi ASSOLUTI per non far impazzire ROS 2
relative_config_imu: "kalibr_imu_chain.yaml"
relative_config_imucam: "kalibr_imucam_chain.yaml"

sim_seed_state_init: 0
sim_seed_preturb: 0
sim_seed_measurements: 0
sim_do_perturbation: false
sim_traj_path: "src/open_vins/ov_data/sim/tum_corridor1_512_16_okvis.txt"
sim_distance_threshold: 1.1
sim_freq_cam: 10
sim_freq_imu: 400
sim_min_feature_gen_dist: 5.0
sim_max_feature_gen_dist: 7.0
