degeneracy_monitor_node:
  ros__parameters:
    kx1: 350.0
    kx2: 750.0
    ky1: 350.0
    ky2: 750.0
    kz1: 350.0
    kz2: 750.0
    delta_t: 0.1
    stagnation_epsilon: 1e-4
    max_stagnation_counts: 5

swipe_spawner:
  ros__parameters:
    gazebo_world: "corridor"
    impact_wall_distance: 0.3

drop_spawner:
  ros__parameters:
    gazebo_world: "corridor"

surface_detector_node:
  ros__parameters:
    min_valid_dist: 0.2
    max_valid_dist: 6.0
    camera_fx: 432.61

vio_recovery_controller_node:
  ros__parameters:
    force_filter_alpha: 0.4


vio_recovery_fsm_node:
  ros__parameters:
    enable_recovery: true                      # If false, the FSM will ignore VIO failures and not trigger recovery
    enable_lateral: false                       # If false, skips lateral wall swipe
    enable_bottom: true                        # If false, skips dropping marker on the ground
    trigger_on_potentially_inconsistent: true  # If false, only triggers on INCONSISTENT state
    min_consistent_to_arm: 10                  # Number of consecutive CONSISTENT messages before FSM arms
    delay_before_drop: 1.5                     # Wait time (seconds) in STOP state before dropping ground marker
    strafe_velocity: 0.10                      # Lateral velocity (m/s) towards the wall
    return_velocity: 0.15                      # Lateral velocity (m/s) when returning to center
    return_distance: 0.50                      # Distance (m) to travel away from the wall during RETURN
    max_strafe_distance: 5.0                   # Maximum distance (m) to strafe before aborting
    swipe_length: 1.0                          # Length (m) of the forward swipe motion
    swipe_velocity: 0.1                        # Forward velocity (m/s) during SWIPE
    impact_force_threshold: 0.5                # Force threshold (N) to detect wall contact

spray_heuristic_node:
  ros__parameters:
    max_reachable_dist: 5.0
    min_features_critical: 30
    max_marker_interval: 5.0

wrench_estimator_node:
  ros__parameters:
    gazebo_world: "corridor"
    gazebo_model: "baby_k_0"
    mass: 2.0
    inertia_xx: 0.0420
    inertia_yy: 0.0280
    inertia_zz: 0.0600
    k_i_f: 10.0
    k_i_m: 20.0
    max_thrust_n: 43.8
    max_torque_nm: 2.5
    max_force_out: 50.0
    max_torque_out: 5.0

flight_odometry_filter_node:
  ros__parameters:
    mass: 2.0
    inertia_xx: 0.0420
    inertia_yy: 0.0280
    inertia_zz: 0.0600
    impact_force_threshold: 0.4
    impact_torque_threshold: 0.5
    enable_tactile_odometry: true
    max_thrust_n: 43.8